<?php
/**
 * Implements hook_init().
 * Apache has already not found the physical file (possibly because it has
 * been migrated to Amazon S3, but we still have hardcoded paths in content.
 * Intercepts certain requests and attempts to hotlink/download the S3 file.
 */
function s3fs_migrate_file_proxy_init() {
  // Make sure we're requesting a file in the files dir
  // Currently this only works for PUBLIC files
  $file_dir = _stage_file_proxy_file_dir();
  if (strpos($_GET['q'], $file_dir) !== 0) {
    return;
  }

  // Process:
  // 1. We know this path doesn't exist locally, so attempt to fetch it
  // 1. Strip path and query local files table for an s3 equiv path
  // 1. Redirect output to that s3 path
  // Q. Does this care about image styles / imagecache?

}
